/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saivenky_neural_c_OutputLayer */

#ifndef _Included_saivenky_neural_c_OutputLayer
#define _Included_saivenky_neural_c_OutputLayer
#ifdef __cplusplus
extern "C" {
#endif
#undef saivenky_neural_c_OutputLayer_SIZEOF_DOUBLE
#define saivenky_neural_c_OutputLayer_SIZEOF_DOUBLE 8L
/*
 * Class:     saivenky_neural_c_OutputLayer
 * Method:    create
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_OutputLayer_create
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     saivenky_neural_c_OutputLayer
 * Method:    destroy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_OutputLayer_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
