/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saivenky_neural_c_Layer */

#ifndef _Included_saivenky_neural_c_Layer
#define _Included_saivenky_neural_c_Layer
#ifdef __cplusplus
extern "C" {
#endif
#undef saivenky_neural_c_Layer_SIZEOF_DOUBLE
#define saivenky_neural_c_Layer_SIZEOF_DOUBLE 8L
/*
 * Class:     saivenky_neural_c_Layer
 * Method:    feedforward
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_c_Layer_feedforward
  (JNIEnv *, jclass, jlong);

/*
 * Class:     saivenky_neural_c_Layer
 * Method:    backpropogate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_c_Layer_backpropogate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     saivenky_neural_c_Layer
 * Method:    update
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_c_Layer_update
  (JNIEnv *, jclass, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
