/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saivenky_neural_c_SigmoidLayer */

#ifndef _Included_saivenky_neural_c_SigmoidLayer
#define _Included_saivenky_neural_c_SigmoidLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     saivenky_neural_c_SigmoidLayer
 * Method:    create
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_SigmoidLayer_create
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     saivenky_neural_c_SigmoidLayer
 * Method:    destroy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_SigmoidLayer_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_c_SigmoidLayer
 * Method:    feedforward
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_c_SigmoidLayer_feedforward
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_c_SigmoidLayer
 * Method:    backpropogate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_c_SigmoidLayer_backpropogate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_c_SigmoidLayer
 * Method:    update
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_c_SigmoidLayer_update
  (JNIEnv *, jobject, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
