/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saivenky_neural_ArrayCImplConvolutionLayer */

#ifndef _Included_saivenky_neural_ArrayCImplConvolutionLayer
#define _Included_saivenky_neural_ArrayCImplConvolutionLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     saivenky_neural_ArrayCImplConvolutionLayer
 * Method:    createNativeLayer
 * Signature: ([I[III)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_ArrayCImplConvolutionLayer_createNativeLayer
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     saivenky_neural_ArrayCImplConvolutionLayer
 * Method:    applyConvolution
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_ArrayCImplConvolutionLayer_applyConvolution
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_ArrayCImplConvolutionLayer
 * Method:    backpropogateToProperties
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_ArrayCImplConvolutionLayer_backpropogateToProperties
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_ArrayCImplConvolutionLayer
 * Method:    updateProperties
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_ArrayCImplConvolutionLayer_updateProperties
  (JNIEnv *, jobject, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
