/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saivenky_neural_c_InputLayer */

#ifndef _Included_saivenky_neural_c_InputLayer
#define _Included_saivenky_neural_c_InputLayer
#ifdef __cplusplus
extern "C" {
#endif
#undef saivenky_neural_c_InputLayer_SIZEOF_DOUBLE
#define saivenky_neural_c_InputLayer_SIZEOF_DOUBLE 8L
/*
 * Class:     saivenky_neural_c_InputLayer
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_InputLayer_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     saivenky_neural_c_InputLayer
 * Method:    destroy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_InputLayer_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
