/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saivenky_neural_c_ConvolutionLayer */

#ifndef _Included_saivenky_neural_c_ConvolutionLayer
#define _Included_saivenky_neural_c_ConvolutionLayer
#ifdef __cplusplus
extern "C" {
#endif
#undef saivenky_neural_c_ConvolutionLayer_SIZEOF_DOUBLE
#define saivenky_neural_c_ConvolutionLayer_SIZEOF_DOUBLE 8L
/*
 * Class:     saivenky_neural_c_ConvolutionLayer
 * Method:    create
 * Signature: ([I[IIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_ConvolutionLayer_create
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jint, jlong);

/*
 * Class:     saivenky_neural_c_ConvolutionLayer
 * Method:    destroy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_ConvolutionLayer_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
