/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saivenky_neural_c_SigmoidLayer */

#ifndef _Included_saivenky_neural_c_SigmoidLayer
#define _Included_saivenky_neural_c_SigmoidLayer
#ifdef __cplusplus
extern "C" {
#endif
#undef saivenky_neural_c_SigmoidLayer_SIZEOF_DOUBLE
#define saivenky_neural_c_SigmoidLayer_SIZEOF_DOUBLE 8L
/*
 * Class:     saivenky_neural_c_SigmoidLayer
 * Method:    create
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_SigmoidLayer_create
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     saivenky_neural_c_SigmoidLayer
 * Method:    destroy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_SigmoidLayer_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_c_SigmoidLayer
 * Method:    feedforward
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_c_SigmoidLayer_feedforward
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_c_SigmoidLayer
 * Method:    backpropogate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_c_SigmoidLayer_backpropogate
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
