/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saivenky_neural_c_FullyConnectedLayer */

#ifndef _Included_saivenky_neural_c_FullyConnectedLayer
#define _Included_saivenky_neural_c_FullyConnectedLayer
#ifdef __cplusplus
extern "C" {
#endif
#undef saivenky_neural_c_FullyConnectedLayer_SIZEOF_DOUBLE
#define saivenky_neural_c_FullyConnectedLayer_SIZEOF_DOUBLE 8L
/*
 * Class:     saivenky_neural_c_FullyConnectedLayer
 * Method:    create
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_FullyConnectedLayer_create
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     saivenky_neural_c_FullyConnectedLayer
 * Method:    destroy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_c_FullyConnectedLayer_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
