/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saivenky_neural_ConvolutionCImplLayer */

#ifndef _Included_saivenky_neural_ConvolutionCImplLayer
#define _Included_saivenky_neural_ConvolutionCImplLayer
#ifdef __cplusplus
extern "C" {
#endif
#undef saivenky_neural_ConvolutionCImplLayer_SIZEOF_DOUBLE
#define saivenky_neural_ConvolutionCImplLayer_SIZEOF_DOUBLE 8L
/*
 * Class:     saivenky_neural_ConvolutionCImplLayer
 * Method:    create
 * Signature: ([I[IIILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_ConvolutionCImplLayer_create
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jobject, jobject);

/*
 * Class:     saivenky_neural_ConvolutionCImplLayer
 * Method:    destroy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_saivenky_neural_ConvolutionCImplLayer_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_ConvolutionCImplLayer
 * Method:    feedforward
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_ConvolutionCImplLayer_feedforward
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_ConvolutionCImplLayer
 * Method:    backpropogate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_ConvolutionCImplLayer_backpropogate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     saivenky_neural_ConvolutionCImplLayer
 * Method:    update
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_saivenky_neural_ConvolutionCImplLayer_update
  (JNIEnv *, jobject, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
